"""
Django settings for nps project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 这一行在PATH中增加了nps文件夹，这样在django项目nps中，任何py都可以import nps下的模块（程序的入口是：apache->modwsgi->nps）
os.path.join(BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1#(3^uarb&*f=)*s@5nvuhuzab_*!qqefexmp%g8(=(k@(5*f#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*",]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'app_nps',
    'app_chatgpt',
    # 'django_celery_beat',
    # 'app_chatgpt.UserProfile',
    # 'app_chatgpt.Role',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app_chatgpt.middlewares.Chatgpt_Middleware',
]

ROOT_URLCONF = 'nps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
            BASE_DIR / "static/phaser",
            BASE_DIR / "static",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'Asia/Shanghai'
# TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, '/static/')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'   # 采用内存session而非缺省的数据库session
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# ========================================================user密码强度规则设置=============================================
AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    #     'OPTIONS': {
    #         'min_length': 6,
    #     }
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    #     'OPTIONS': {
    #         'password_list_path': None  # 禁用常见密码检查
    #     }
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', #禁用全为数字的密码
    # },
]


# ========================================================celery配置====================================================
# 配置Brocker和Backend参数为Redis地址以及数据库编号，默认使用0号库。
BROKER_URL = 'redis://localhost:6379/0'
# CELERY_BROKER_URL = 'redis://localhost:6379/0'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# 将自己创建的app添加到INSTALLED_APP中，并设置包含task模块路径名（tasks.check_expired_accounts）所需字段。
# INSTALLED_APPS += [
#     'app_chatgpt.Chat_GPT',
# ]

# Celery worker 进程数量。默认是服务器CPU核心数加上一倍，例如：本机为双核四线程，则这里会启动8个进程。
CELERY_WORKER_CONCURRENCY = 4

# 异步方式处理任务队列
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_SERIALIZER = "json"
CELERY_ENABLE_UTC = True

TIME_ZONE = 'Asia/Shanghai'
CELERY_TIMEZONE = TIME_ZONE
# ======================================================================================================================
the_setting_dict = {
    "BASE_DIR: ": BASE_DIR,
    "INSTALLED_APPS: ": INSTALLED_APPS,
    "ROOT_URLCONF: ": ROOT_URLCONF,
    "DATABASES: ": DATABASES,
    "STATIC_URL: ": STATIC_URL,
    "STATIC_ROOT: ": STATIC_ROOT,
    "STATICFILES_DIRS: ": STATICFILES_DIRS,
    "SESSION_ENGINE: ": SESSION_ENGINE,
}
print("=======================================Django started=====================================", end="")
print("[Django main settings]: ", the_setting_dict, end='')
print("[Attentions]: Django main thread starts from apache. So INSTALLED_APPS errors from console program are normal.", end="")
print("=======================================Django started=====================================", end="")

